#!/usr/bin/env python3
"""MPKI profiling driver + R2 suite selection.

Drives gem5/configs/dprh/run_se.py --config B1 over every runnable SPEC SE-mode
benchmark for a fixed-offset measurement window, parses each stats.txt for LLC
misses and committed instructions, computes

    LLC_MPKI = LLC_demand_misses / (simInsts / 1000)

and writes results/mpki_profile.csv plus the selected suites:
  - R2 main set:      per-benchmark LLC MPKI >= 1
  - R3 no-harm ctrls: LLC MPKI < 0.5
  - R5 held-out:      2-3 traces chosen MECHANICALLY from R2 (see
     select_held_out) and written to results/HELD_OUT.md, so the held-out set is
     registered at profiling time -- before any tuning run can contaminate it
     (FIX-4). Enforced downstream by scripts/dispatch_guard.py.

This script is [cluster]-run (it invokes gem5.opt). On macOS it is authored and
syntax-checked only; run it on the Linux cluster after SPEC is cross-compiled.

Benchmark discovery: --benchmarks-dir is scanned for a manifest file
`benchmarks.tsv` with lines: "<name>\t<binary_path>\t<args>". If absent, every
executable directly under --benchmarks-dir is treated as a benchmark with no
args. Excluded benchmarks (SE-mode-incompatible) belong in benchmarks/README.md
and should simply be omitted from the manifest.

LLC cache stat path: system.llc.demandMisses::total (run_se.py names the LLC
`system.llc`). Falls back to overallMisses::total, then any *.llc.*Misses total.
"""
import argparse
import csv
import datetime
import os
import re
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEM5 = os.path.join(REPO_ROOT, "gem5", "build", "X86", "gem5.opt")
RUN_SE = os.path.join(REPO_ROOT, "gem5", "configs", "dprh", "run_se.py")

LLC_MISS_STATS = [
    "system.llc.demandMisses::total",
    "system.llc.overallMisses::total",
]
INSTS_STATS = ["simInsts", "system.o3.numInsts", "system.o3.committedInsts"]


def parse_stat(text, names):
    for name in names:
        m = re.search(
            r"^" + re.escape(name) + r"\s+([-\d.eE+]+)", text, re.MULTILINE
        )
        if m:
            return float(m.group(1))
    return None


def discover_benchmarks(bench_dir):
    manifest = os.path.join(bench_dir, "benchmarks.tsv")
    benches = []
    if os.path.isfile(manifest):
        with open(manifest) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                name = parts[0]
                binary = parts[1] if len(parts) > 1 else ""
                bargs = parts[2] if len(parts) > 2 else ""
                benches.append((name, binary, bargs))
    else:
        for entry in sorted(os.listdir(bench_dir)):
            path = os.path.join(bench_dir, entry)
            if os.path.isfile(path) and os.access(path, os.X_OK):
                benches.append((entry, path, ""))
    return benches


def run_one(name, binary, bargs, measure, ff_offset, outroot):
    outdir = os.path.join(outroot, f"mpki_{name}")
    cmd = [
        GEM5, f"--outdir={outdir}", RUN_SE,
        "--config", "B1", "--prefetcher", "spp",
        "--cmd", binary,
        "--ff-offset", str(ff_offset),
        "--warmup", "0",
        "--measure", str(measure),
    ]
    if bargs:
        cmd += ["--options", bargs]
    print(f"[mpki] running {name}: {' '.join(cmd)}")
    subprocess.run(cmd, check=False)
    stats_path = os.path.join(outdir, "stats.txt")
    if not os.path.isfile(stats_path):
        return None, None
    with open(stats_path) as f:
        text = f.read()
    misses = parse_stat(text, LLC_MISS_STATS)
    insts = parse_stat(text, INSTS_STATS)
    return misses, insts


HELD_OUT_STRIDE = 5
HELD_OUT_MAX = 3


def select_held_out(r2_ranked, stride=HELD_OUT_STRIDE, max_n=HELD_OUT_MAX):
    """Mechanical R5 held-out selection (no curation).

    r2_ranked: R2 benchmark names already sorted by DESCENDING LLC MPKI (rank 1
    = highest MPKI). Returns the held-out names: every `stride`-th benchmark by
    rank (ranks stride, 2*stride, ...), capped at max_n. Fallback for a small R2
    (fewer than `stride` members): the single median-rank member, so the result
    is deterministic and never silently empty when R2 is non-empty.
    """
    picks = r2_ranked[stride - 1::stride][:max_n]
    if not picks and r2_ranked:
        picks = [r2_ranked[len(r2_ranked) // 2]]
    return picks


def write_held_out(path, held, r2_ranked, mpki_by, r2_threshold, csv_path,
                   stride=HELD_OUT_STRIDE, max_n=HELD_OUT_MAX):
    """Write results/HELD_OUT.md: the mechanically-selected R5 set + the rule."""
    ranks = ", ".join(str(stride * k) for k in range(1, max_n + 1))
    lines = [
        "# DPRH R5 Held-Out Set (AUTO-GENERATED by scripts/mpki_profile.py "
        "-- do not edit)",
        "",
        f"Generated: {datetime.datetime.now().isoformat(timespec='seconds')}",
        f"Source: {csv_path}",
        "",
        "## Selection rule (mechanical, not curated)",
        f"From the R2 set (LLC MPKI >= {r2_threshold}) sorted by descending "
        f"MPKI, take every {stride}th benchmark by rank (ranks {ranks}), capped "
        f"at {max_n}. Fallback if R2 has < {stride} members: the single "
        f"median-rank R2 benchmark.",
        "",
        "## Held-out traces (EXCLUDED FROM ALL TUNING)",
    ]
    if held:
        for name in held:
            rank = r2_ranked.index(name) + 1
            lines.append(f"- {name}  (rank {rank}, MPKI {mpki_by.get(name)})")
    else:
        lines.append("- (none -- R2 set was empty)")
    lines += [
        "",
        "Enforcement: scripts/dispatch_guard.py refuses to run these unless "
        "--final-run is passed (each such run is logged to "
        "results/final_run.log).",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def _selftest():
    """Assert the held-out rule is mechanical + deterministic (no gem5)."""
    r2 = [f"b{i:02d}" for i in range(15)]          # ranks 1..15
    assert select_held_out(r2) == ["b04", "b09", "b14"], select_held_out(r2)
    assert len(select_held_out([f"b{i:02d}" for i in range(30)])) == 3
    assert select_held_out(r2) == select_held_out(list(r2))   # deterministic
    assert select_held_out(["x", "y", "z"]) == ["y"]          # small fallback
    assert select_held_out([]) == []                          # empty
    print("[mpki] selftest OK (mechanical R5 selection)")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selftest", action="store_true",
                    help="run mechanical-selection self-tests and exit "
                         "(no gem5, no benchmarks needed)")
    ap.add_argument("--benchmarks-dir")
    ap.add_argument("--measure", type=int, default=50_000_000)
    ap.add_argument("--ff-offset", type=int, default=1_000_000_000)
    ap.add_argument("--out", default=os.path.join(REPO_ROOT, "results",
                                                  "mpki_profile.csv"))
    ap.add_argument("--outroot", default=os.path.join(REPO_ROOT, "m5out"))
    ap.add_argument("--r2-threshold", type=float, default=1.0)
    ap.add_argument("--r3-threshold", type=float, default=0.5)
    args = ap.parse_args()

    if args.selftest:
        return _selftest()

    if not args.benchmarks_dir:
        print("[mpki] ERROR: --benchmarks-dir is required (or use --selftest)",
              file=sys.stderr)
        return 2

    if not os.path.isfile(GEM5):
        print(f"[mpki] ERROR: gem5.opt not found at {GEM5} -- build on the "
              f"cluster first (scripts/build_gem5.sh).", file=sys.stderr)
        return 2

    benches = discover_benchmarks(args.benchmarks_dir)
    if not benches:
        print(f"[mpki] ERROR: no benchmarks found under "
              f"{args.benchmarks_dir}", file=sys.stderr)
        return 2

    results = []
    for name, binary, bargs in benches:
        misses, insts = run_one(name, binary, bargs, args.measure,
                                 args.ff_offset, args.outroot)
        if misses is None or insts is None or insts <= 0:
            mpki = None
        else:
            mpki = misses / (insts / 1000.0)
        results.append({
            "benchmark": name, "llc_misses": misses,
            "sim_insts": insts, "llc_mpki": mpki,
        })

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["benchmark", "llc_misses", "sim_insts", "llc_mpki",
                        "class"],
        )
        w.writeheader()
        r2, r3 = [], []
        for r in results:
            mpki = r["llc_mpki"]
            if mpki is None:
                cls = "ERROR"
            elif mpki >= args.r2_threshold:
                cls = "R2_main"
                r2.append(r["benchmark"])
            elif mpki < args.r3_threshold:
                cls = "R3_control"
                r3.append(r["benchmark"])
            else:
                cls = "middle"
            r["class"] = cls
            w.writerow(r)

    # FIX-4: register the R5 held-out set MECHANICALLY, here at profiling time,
    # so it is fixed before any tuning run can contaminate it.
    r2_entries = [(r["benchmark"], r["llc_mpki"]) for r in results
                  if r["llc_mpki"] is not None
                  and r["llc_mpki"] >= args.r2_threshold]
    r2_entries.sort(key=lambda nm: (-nm[1], nm[0]))   # descending MPKI, then name
    r2_ranked = [n for n, _ in r2_entries]
    mpki_by = {n: m for n, m in r2_entries}
    held = select_held_out(r2_ranked)
    held_path = os.path.join(os.path.dirname(args.out), "HELD_OUT.md")
    write_held_out(held_path, held, r2_ranked, mpki_by, args.r2_threshold,
                   args.out)

    print(f"\n[mpki] wrote {args.out}")
    print(f"[mpki] R2 main set (MPKI >= {args.r2_threshold}): {r2}")
    print(f"[mpki] R3 no-harm controls (MPKI < {args.r3_threshold}): {r3}")
    print(f"[mpki] wrote {held_path}")
    print(f"[mpki] R5 held-out (mechanical, every-{HELD_OUT_STRIDE}th by rank): "
          f"{held}")
    print("[mpki] Copy R2/R3/R5 into results/PHASE_LOG.md; do NOT hand-pick R5 "
          "-- it is registered in HELD_OUT.md and enforced by dispatch_guard.py.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
